### ISSUE TITLE
arsenal

### ISSUE THREAD

**Issue by ChloeTax** [ChloeTax/hexxytest3#44]
https://modrinth.com/mod/arsenal
from https://github.com/ChloeTax/hexxytest3/issues/43

**Comment by abilliontrillionstars** [comment]
basically a +1 to what Chloe said, there'll be a lot of overlap with Truly Modular. I personally could see it being an _alternative_ to Truly Modular, but we'd need to compile the differences and/or pros-cons. I'd say have someone test it and see what people'd like more, but keep in mind this is all not mention possible incompat

**Comment by walksanatora** [comment]
yes but arsenal adds more *unique* weapons.
also imo truly modular kinda sucks. since it only has material stats but it doesn't appear to keep any material properties. like bedrock dust being unbreakable. or mana/terrasteel being unbreakable.

**Comment by walksanatora** [comment]
also backslot is kinda fun

**Comment by Stick404** [comment]
Pack crashes on startup with Arsenal
```Exception caught from launcher
java.lang.RuntimeException: Non-unique Mixin config name arsenal.mixins.json used by the mods arsenal and tm_arsenal
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:91)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR```

**Comment by walksanatora** [comment]
what even is `tm_arsenal`

**Comment by walksanatora** [comment]
oh tm_arsenal is truly_modular arsenal

**Comment by walksanatora** [comment]
i can probally fix this

**Comment by walksanatora** [comment]
fixed in https://github.com/Truly-Modular/Arsenal/commit/926e519940cc5c5f02c81c75000f0757a47fd754

**Comment by walksanatora** [comment]
(is there a tag for "pending update")

**Comment by walksanatora** [comment]
in the mean time should we add [Ratatouille](https://modrinth.com/mod/ratatouille) just so we can have the plushies on test server

**Comment by walksanatora** [comment]
(it would be added with arsenal anyways)
